receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'nexuscore-mesh-services'
          scrape_interval: 10s
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true

processors:
  batch:
    timeout: 1s
    send_batch_size: 256
  memory_limiter:
    check_interval: 1s
    limit_percentage: 85
    spike_limit_percentage: 15

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "nexuscore"
  loki:
    endpoint: "http://loki-write.nexuscore-infra.svc.cluster.local:3100/loki/api/v1/push"
  otlp/jaeger:
    endpoint: "jaeger-collector.nexuscore-infra.svc.cluster.local:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]
  telemetry:
    logs:
      level: "info"